### ISSUE TITLE
Request: How much bitcoin would you get for a dollar

### ISSUE THREAD

**Issue by rachidbm** [Jorijn/sat.trading#18]
I'm a happy user of sat.trading but sometimes I miss the ability to calculate how much euro's I have to pay for a particular BTC price, like for example transaction fees of `0.0005` BTC. I can convert it easily in google, but I would prefer to not use google.

So what do you think of supporting BTC as well? If you think this would be an addition I'm happy to contribute a pull request to make this happen. For me personally it would be nice if there's a direct URL for calculating BTC, like for example: sat.trading/btc. 

Please let me know what you think and if/how this could be incorporated in the existing page.

**Comment by Jorijn** [comment]
Hey @rachidbm 

I want to redirect you to my response in !19. 

If you remember that one Bitcoin holds 100.000.000 sat, you could easily look up the price for 50k sat.

Jorijn

**Comment by rachidbm** [comment]
I understand that BTC is not in line with the philosophy of the tool, hence the name SAT.trading :-D

My main goal to to convert prices that are expressed in BTC like `0.0005` or `.001` in other places. Until those prices are expressed otherwise I need to do some calculation myself. The reason I tried to contribute to the tool is that I can leverage its hosting and domain name and have multiple options in 1 "place". 
And what about a secret page on sat.trading/btc which doesn't have to be promoted to the outside world? If not, I will look into something myself :)

**Comment by Jorijn** [comment]
Hey @rachidbm 

Hidden pages don't really fit my idea of simple software either. Sorry :)
