### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Sebastix** [Jorijn/sat.trading#8]
![20210411_satstrading-logo-1](https://user-images.githubusercontent.com/582669/114439305-2071e900-9bc9-11eb-8862-0e11e834684f.png)

![20210411_satstrading-logo-2](https://user-images.githubusercontent.com/582669/114439137-f3253b00-9bc8-11eb-9710-981e622a26b8.png)

Please give me your thoughts

**Comment by Sebastix** [comment]
![20210411_satstrading-logo-3](https://user-images.githubusercontent.com/582669/114440405-5ebbd800-9bca-11eb-9ea7-96f2a2318d02.png)

**Comment by Jorijn** [comment]
Hey @Sebastix 

Great work so far. It's certainly an improvement! 

Here are some thoughts:

* The main title is sat.trading, sats.trading works but isn't publically advertised. 
* I like the idea of combining the "ST" characters, but frankly, I don't think it's working for the brand. I do like the smaller B as the Bitcoin logo itself. 

I like the preview of the website. I'm leaning more towards using the B-logo with "sat.trading" as the website's header. We then could replace the current assets (for the home screen, favicon, etc.) with the smaller B.

Looking forward to hearing your thoughts.

Jorijn

**Comment by Sebastix** [comment]
@Jorijn Thanks for the feedback! Quick update:

<img width="706" alt="Schermafbeelding 2021-04-13 om 22 25 17" src="https://user-images.githubusercontent.com/582669/114616464-2f2ecd80-9ca7-11eb-8e3e-15c2cb7d536f.png">

Is this what you've got in your mind with a lowercase / smaller B?

**Comment by Sebastix** [comment]
@Jorijn Check this out: https://github.com/apotdevin/thunderhub/releases/tag/v0.12.14

```
Changes
- chore: add satoshi symbol
```

https://github.com/apotdevin/thunderhub/commit/77c7462430cf24988329d64f85e6c3d6c6d75807

After some searching on the web
https://satsymbol.com/

**Comment by Jorijn** [comment]
Hey! 

No, I meant to drop the ST icon and make the B uppercase. The icon website is really cool, I like it. I don't think it a good brand visual though, it should resemble Bitcoin :)

**Comment by Sebastix** [comment]
![Schermafbeelding 2021-04-20 om 09 16 35](https://user-images.githubusercontent.com/582669/115353796-3a0ec400-a1b9-11eb-98d5-a680051f2abb.png)
![Schermafbeelding 2021-04-20 om 09 16 14](https://user-images.githubusercontent.com/582669/115353808-3c711e00-a1b9-11eb-9536-5d3956ece2b5.png)

Update! The Bitcoin logo with the text sat.trading with the font Ubuntu Bold Italic

**Comment by Sebastix** [comment]
@Jorijn Please check #11

**Comment by Jorijn** [comment]
Looking good! Minor comments:

* Please create a bit more padding, like in the screenshot.
* Double check how it looks on non-dark mode devices. It's showing the wrong logo I think
* Could you update the app & favicon icons to also make use of this B-icon? I like the padding more as opposed to the current icon(s).

Thanks a lot so far 👍

**Comment by Sebastix** [comment]
1. Margin added to the logo (top and bottom with 20px)
2. Good one! Didn't checked that. Added some logic for it. Didn't find quickly a solution when you change the color-schema in the browser the logo also changes.
3. All icons updated

Thanks!

**Comment by Jorijn** [comment]
Hey @Sebastix 

There are two ways;

1) You can add a div with the exact size of the requested logo. Use CSS media queries to fill the light or dark logo.
2) You can use a Vue component and swap out the logo depending on JS rules.

Do you need any help or are you okay with this?

**Comment by Sebastix** [comment]
1. That method is clear for me, but I like the second method more.
2. How does Vue.js handle the event when changing the color-system property? That's was the answer I was looking for.

```window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change",   e => e.matches && activateDarkMode() ); ```

Can this snippet do the job?

**Comment by Jorijn** [comment]
Looks like it :-) https://www.ajaypalcheema.com/dark-mode-js/

**Comment by Sebastix** [comment]
@Jorijn Added the logo as a component now with the color system logic. Please check the changes in #11 =)

**Comment by Jorijn** [comment]
Looking good! I left a minor comment for something I noticed. The rest looks good to me. If you fix this, I'll merge. Thanks again :)

**Comment by Sebastix** [comment]
Fixed!

**Comment by Jorijn** [comment]
Merged! Thank you.
